Pizzeria/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path
from . import views 


app_name = 'pizzas'

urlpatterns = [ 
    path('',views.index,name='index'),
    path('pizza',views.pizza,name='pizza'),
    path('pizza/<int:pizza_id>/',views.pizzas,name='pizzas'),
    #path('pizza/<int:pizza_id>/', views.addcomment, name='addcomment')
    path('addcomment/<int:pizza_id>/', views.addcomment, name='addcomment')
]

pizzas/models.py
from django.db import models


# Create your models here.
## model = Pizza
## field = pizza_name (Hawaiian, Meat Lovers, etc.)
class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name

## model = Topping
## field 1 = pizza - FK
## field 2 = topping_name (Pineapple, Canadian bacon, sausage, etc.)
class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    pizza_name = models.TextField()

    def __str__(self):
        return self.pizza_name 

## comments 
class Comment(models.Model):
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    text = models.TextField(max_length=200)

    def __str__(self):
        return self.text

pizzas/forms.py
from django import forms
from .models import *

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','text','id')

pizzas/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    return render(request, 'pizzas/index.html')


def pizza(request):
    pizza = Pizza.objects.all()

    context = {'all_pizza':pizza}

    return render(request, 'pizzas/pizza.html', context)

def pizzas(request, pizza_id):
    p = Pizza.objects.get(id=pizza_id)

    toppings = Topping.objects.filter(pizza=p)

    context = {'pizzas':p,'toppings':toppings}

    return render(request, 'pizzas/pizzas.html', context)


def addcomment(request, pizza_id):
    if request.method == 'POST' and request.POST.get("btn1"):
        comment = request.POST.get("comment") 
        pizza = request.POST.get("id") 
        Comment.objects.create(pizza=pizza_id, text=comment)
        #Comment.objects.create(text=comment)

    addcomment = Comment.objects.filter(pizza=pizza_id)
    pizza = Pizza.objects.get(id=pizza_id)

    context = {'pizza':pizza, 'addcomment':addcomment}
    return render(request, 'pizzas/addcomment.html', context)

pizzas/templates/pizzas/addcomment.html
{% extends "pizzas/base.html" %} 

{% block content %}

<h2><p>Pizza: {{ pizza.pizza_name }} </p></h2>

<form method="POST">
    {% csrf_token %} 
    {{ form.as_p }}
    {% for c in comments %}
    <ul>
        <p>{{ c.name }} -- {{ c.text }}</p>
    </ul>
    {% empty %} 
    <ul>There are no comments for this post.</ul>
    {% endfor %} 

<p><input type="text" name="comment"></p>
<p><button type="submit" name="btn1" value=1>Submit Comment</button></p>

</form>
{% endblock content %} 

pizzas/templates/pizzas/base.html
<html lang="en">
<head>
        {% block title %}<title>Pizzeria</title>{% endblock %}
        <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
  {% load static %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <ul><a href="{% url 'pizzas:index' %}">
                        <p style="font-family:'Verdana';font-size:110%;">
                            Home</a></ul></p>

                    <ul><a href="{% url 'pizzas:pizza' %}">
                        <p style="font-family:'Verdana';font-size:110%;">
                        Pizzas</a></ul></p>
                </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
</div>
    </div>
    </div>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %} 

{% block content %}

{% load static %}

<body style="background-color:darkgray">
</body>

<h1 style="font-family:'Bodoni 72 Smallcaps';font-size:300%;color:darkred">
    <strong>Welcome to the Pizzeria!</strong>
</h1>


<p style="font-family:'Copperplate';color:black;font-size:120%">
    Select 'Pizzas' to view our available pizzas!
</p>


<html>
<body>
    
    <img src="{% static 'homepizza.jpeg' %}">
</body>
</html>

{% endblock content %} 

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %} 

{% block content %}

{% load static %}

<body style="background-color:darkgray">
</body>


<h1 style="font-family:'Copperplate';font-size:220%;color:darkred">
    Available Pizzas
</h1>


<ul>
    {% for p in all_pizza %}

    <li> 
        <a href="{% url 'pizzas:pizzas' p.id %}"> 
            <p style="font-family:'Didot';font-size:130%;">
                {{ p }}</a></li></p>
    </li>


    {% empty %}
    <li> No pizzas have been added yet. </li>
    {% endfor %}

</ul>
<html>
<body>

    <img src="{% static 'hawaiianpizza.jpg' %}">
    <img src="{% static 'meatlovers.jpeg' %}">
    <img src="{% static 'veggiepizza.jpg' %}">
    <img src="{% static 'cheesepizza.jpeg' %}">

</body>
</html>

{% endblock content %} 

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %} 
{% load static %}

{% block content %}

<body style="background-color:darkgray">
</body>

<h1 style="font-family:'Copperplate';font-size:220%;color:darkred">
Pizzas: {{ pizzas }}
</h1>

<ul>
    {% for t in toppings %}
    <li style="font-family:'Didot';font-size:130%;">
        {{ t }}
    </li>

    {% empty %}
    <li> No toppings for this pizza has been added yet. </li>
    {% endfor %}
</ul>

<br><br>

<td>Comments: &nbsp <a href="{% url 'pizzas:addcomment' 1 %}">Add a new comment</a>
</td>


{% endblock content %} 